export const L1_STATUS = [
   "DND",
   "Number Not Reachable",
   "Wrong Number",

   "NE-Fresher",
   "NI-In-Job",
   "NE-Experienced",
   "NI-Convincing",
   "WD",
   "TAC",
   "GOOD",
].sort();
export const L2_STATUS = [
   null,
   "DND",
   "Number Not Reachable",
   "Wrong Number",
   "Blacklist",
   "NE-Fresher",
   "NI-In-Job",
   "NE-Experienced",
   "NI-Convincing",
   "WD",
   "TAC",
   "GOOD",
].sort();
export const PERIOD_LIST = ["Permanent", "Contract", "Notice Period", "Buyout"].sort();
export const INTERVIEW_STATUS = [
   "TPP Venue",
   "Client Venue",
   "Virtual Interview",
   "Reject FSR Communication",
   "Reject FSR Stability",
   "Reject FSR Domain",
   "Reject Amcat",
   "Reject Amcat - Technical Issue Reject Amcat Cooling Period",
   "Reject Versant",
   "Reject Versant - Technical Issue",
   "Reject Versant Cooling Period",
   "Reject Technical",
   "Reject Typing",
   "Reject Group Discussion",
   "Reject Ops/Client Communication",
   "Reject Ops/Client Stability",
   "Reject Ops/Client Domain",
   "Reject Training",
   "No Show Walk-in",
   "No Show IC",
   "Hold",
   "Pending FSR",
   "Pending Amcat",
   "Pending Versant",
   "Pending Technical",
   "Pending Typing",
   "Pending Group Discussion",
   "Pending Ops",
   "Pending Training",
   "Offer Drop",
   "Select",
   "TPP Venue-R",
   "Client Venue-R",
   "Virtual-R",
   "Pending Re-Versant",
   "Pending Re-Amcat",
   "Source Conflict",
   "Pending Client",
   "TPP FT",
   "TPP Intern",
   "Cooling Period",
   "BGV Reject-Pre",
].sort();

export const EMPLOYEE_TYPE = [
   "Recruiter",
   "Teamlead",
   "Manager",
   "Intern",
   "Business Development",
   "Admin",
].sort();
export const RESPONSE = [
   "Empanelled",
   "Need to Approach",
   "In Process",
   "Future",
   "Not Intrested",
   "Rejected",
   "No Response",
].sort();
export const PROCESS_TYPE = ["International", "Domestic"].sort();
export const SELECT_STATUS = [
   "Tracking",
   "Non Tenure",
   "Need to Bill",
   "Billed",
   "Process Rampdown",
   "Client Rampdown",
   "Invoice Processed",
   "BGV Reject-Post",
   "Tenure-Source Conflict",
   "Billed & Tracking",
   "Tracking & NR",
].sort();
export const LANGUAGE_LEVEL = [
   "Poor",
   "Managable",
   "Above Managable",
   "Excellent",
].sort();

export const SOURCE = [
   "Candidate Reference",
   "Personal Reference",
   "Direct Walkin",
   "TPP Social Media",
   "CEO Reference",
   "Naukri",
   "FoundIT",
   "Quikr",
   "Shine",
   "Apna",
   "Indeed",
   "LinkedIn",
   "SubVendor/Freelancer",
   "Old Data",
   "Bulk Data",
].sort();